apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: mcp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      containers:
      - name: mcp-gateway
        image: your-registry/mcp-gateway:latest   # replace with your image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: mcp-demo
spec:
  selector:
    app: mcp-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
