apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: mcp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: your-registry/mcp-server:latest   # replace with your image
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp-demo
spec:
  selector:
    app: mcp-server
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
